-- Tenant integrity and server-owned assessment timestamps.
--
-- Additive only: one unique index, three foreign keys, four CHECK constraints,
-- one trigger function and three triggers. No column, constraint or row is
-- dropped or modified.
--
-- Prisma models the index and foreign keys (schema.prisma, `companyTenant`).
-- It cannot model CHECK constraints or triggers; those live only here, and
-- Prisma leaves objects it does not model untouched.


-- 1. Pre-flight --------------------------------------------------------------
-- Runs before any DDL. If existing data already crosses a tenant boundary or
-- carries a future timestamp, the migration stops here with a count and nothing
-- has been changed. Such rows need a human decision, not silent repair.

DO $$
DECLARE
  cross_tenant_companies bigint;
  future_timestamps bigint;
  non_member_references bigint;
BEGIN
  SELECT
    (SELECT count(*) FROM "public"."tasks" t
       JOIN "public"."companies" c ON c."id" = t."companyId"
      WHERE c."organizationId" <> t."organizationId")
  + (SELECT count(*) FROM "public"."incidents" i
       JOIN "public"."companies" c ON c."id" = i."companyId"
      WHERE c."organizationId" <> i."organizationId")
  + (SELECT count(*) FROM "public"."reports" r
       JOIN "public"."companies" c ON c."id" = r."companyId"
      WHERE c."organizationId" <> r."organizationId")
  INTO cross_tenant_companies;

  SELECT
    (SELECT count(*) FROM "public"."readiness_scores"
      WHERE "checkedAt" > now() + interval '5 minutes')
  + (SELECT count(*) FROM "public"."companies"
      WHERE "lastCheckedAt" > now() + interval '5 minutes')
  + (SELECT count(*) FROM "public"."readiness_scans"
      WHERE "startedAt" > now() + interval '5 minutes'
         OR "completedAt" > now() + interval '5 minutes')
  INTO future_timestamps;

  IF cross_tenant_companies > 0 OR future_timestamps > 0 THEN
    RAISE EXCEPTION
      'tenant_integrity pre-flight failed: % cross-organization company reference(s), % future timestamp(s). Nothing was changed.',
      cross_tenant_companies, future_timestamps
      USING HINT = 'Inspect and resolve these rows, then run prisma migrate deploy again.';
  END IF;

  -- User references are checked on write only (see section 4), because a user
  -- who has since left an organization legitimately remains on its history.
  -- Existing references to non-members are therefore reported, not refused.
  SELECT count(*) INTO non_member_references FROM (
    SELECT t."organizationId" AS org, t."assignedToId" AS usr FROM "public"."tasks" t WHERE t."assignedToId" IS NOT NULL
    UNION ALL
    SELECT t."organizationId", t."createdById" FROM "public"."tasks" t WHERE t."createdById" IS NOT NULL
    UNION ALL
    SELECT r."organizationId", r."generatedById" FROM "public"."reports" r WHERE r."generatedById" IS NOT NULL
    UNION ALL
    SELECT c."organizationId", s."completedById" FROM "public"."readiness_scans" s
      JOIN "public"."companies" c ON c."id" = s."companyId" WHERE s."completedById" IS NOT NULL
  ) refs
  WHERE NOT EXISTS (
    SELECT 1 FROM "public"."memberships" m
     WHERE m."organizationId" = refs.org AND m."userId" = refs.usr
  );

  IF non_member_references > 0 THEN
    RAISE NOTICE
      'tenant_integrity: % existing user reference(s) point at users who are not current members. Kept as history; new writes will be refused.',
      non_member_references;
  END IF;
END
$$;


-- 2. Company references stay inside their organization ------------------------
-- Generated by `prisma migrate diff`. The existing single-column foreign keys
-- (ON DELETE SET NULL) stay; these composite keys only add the tenant check.
-- MATCH SIMPLE means a NULL companyId is never checked.

-- CreateIndex
CREATE UNIQUE INDEX "companies_id_organizationId_key" ON "public"."companies"("id", "organizationId");

-- AddForeignKey
ALTER TABLE "public"."tasks" ADD CONSTRAINT "tasks_companyId_organizationId_fkey" FOREIGN KEY ("companyId", "organizationId") REFERENCES "public"."companies"("id", "organizationId") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "public"."incidents" ADD CONSTRAINT "incidents_companyId_organizationId_fkey" FOREIGN KEY ("companyId", "organizationId") REFERENCES "public"."companies"("id", "organizationId") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "public"."reports" ADD CONSTRAINT "reports_companyId_organizationId_fkey" FOREIGN KEY ("companyId", "organizationId") REFERENCES "public"."companies"("id", "organizationId") ON DELETE NO ACTION ON UPDATE NO ACTION;


-- 3. Assessment timestamps cannot lie in the future ----------------------------
-- The server sets these, but the database refuses future values regardless of
-- which code path writes them. Five minutes absorbs clock skew between the API
-- host and the database. A value that is valid when written only becomes more
-- valid as time passes, so these checks stay true on restore.

ALTER TABLE "public"."readiness_scores"
  ADD CONSTRAINT "readiness_scores_checkedAt_not_future"
  CHECK ("checkedAt" <= now() + interval '5 minutes');

ALTER TABLE "public"."companies"
  ADD CONSTRAINT "companies_lastCheckedAt_not_future"
  CHECK ("lastCheckedAt" IS NULL OR "lastCheckedAt" <= now() + interval '5 minutes');

ALTER TABLE "public"."readiness_scans"
  ADD CONSTRAINT "readiness_scans_startedAt_not_future"
  CHECK ("startedAt" <= now() + interval '5 minutes');

ALTER TABLE "public"."readiness_scans"
  ADD CONSTRAINT "readiness_scans_completedAt_not_future"
  CHECK ("completedAt" IS NULL OR "completedAt" <= now() + interval '5 minutes');


-- 4. User references must be members of the row's organization ----------------
-- A foreign key to memberships would also block removing a member while any
-- historical task or report still names them. This trigger instead checks at
-- write time: a user can only be newly assigned, credited or recorded while they
-- are a member. Rows that already name them keep doing so after they leave, and
-- updates that do not change the user or the organization are not re-checked.
--
-- Arguments: the organization column (or '@company' to resolve it through
-- companyId), followed by one or more user id columns.

CREATE FUNCTION "public"."enforce_tenant_membership"() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  new_row jsonb := to_jsonb(NEW);
  old_row jsonb := CASE WHEN TG_OP = 'UPDATE' THEN to_jsonb(OLD) ELSE NULL END;
  org_column text := TG_ARGV[0];
  org_id text;
  org_changed boolean;
  user_column text;
  user_id text;
  i integer;
BEGIN
  IF org_column = '@company' THEN
    SELECT c."organizationId" INTO org_id
      FROM "public"."companies" c WHERE c."id" = new_row->>'companyId';
    org_changed := TG_OP = 'INSERT'
      OR (old_row->>'companyId') IS DISTINCT FROM (new_row->>'companyId');
  ELSE
    org_id := new_row->>org_column;
    org_changed := TG_OP = 'INSERT'
      OR (old_row->>org_column) IS DISTINCT FROM (new_row->>org_column);
  END IF;

  FOR i IN 1 .. TG_NARGS - 1 LOOP
    user_column := TG_ARGV[i];
    user_id := new_row->>user_column;

    CONTINUE WHEN user_id IS NULL;
    CONTINUE WHEN NOT org_changed
      AND (old_row->>user_column) IS NOT DISTINCT FROM user_id;

    IF NOT EXISTS (
      SELECT 1 FROM "public"."memberships" m
       WHERE m."organizationId" = org_id AND m."userId" = user_id
    ) THEN
      RAISE EXCEPTION
        '%.% must reference a member of organization %', TG_TABLE_NAME, user_column, org_id
        USING ERRCODE = 'foreign_key_violation';
    END IF;
  END LOOP;

  RETURN NEW;
END
$$;

CREATE TRIGGER "tasks_enforce_tenant_membership"
  BEFORE INSERT OR UPDATE OF "organizationId", "assignedToId", "createdById"
  ON "public"."tasks"
  FOR EACH ROW
  EXECUTE FUNCTION "public"."enforce_tenant_membership"('organizationId', 'assignedToId', 'createdById');

CREATE TRIGGER "reports_enforce_tenant_membership"
  BEFORE INSERT OR UPDATE OF "organizationId", "generatedById"
  ON "public"."reports"
  FOR EACH ROW
  EXECUTE FUNCTION "public"."enforce_tenant_membership"('organizationId', 'generatedById');

CREATE TRIGGER "readiness_scans_enforce_tenant_membership"
  BEFORE INSERT OR UPDATE OF "companyId", "completedById"
  ON "public"."readiness_scans"
  FOR EACH ROW
  EXECUTE FUNCTION "public"."enforce_tenant_membership"('@company', 'completedById');
